version: "3.3"

services:
  server:
    build:
      context: ../
      dockerfile: docker/server/Dockerfile
    ports:
      - 7171:7171
      - 7172:7172
    volumes:
      - ../data/:/otbr/data/
    depends_on:
      - mysql
      - login
    links:
      - mysql

  mysql:
    build:
      context: ../
      dockerfile: docker/mysql/Dockerfile
    restart: unless-stopped
    environment:
      - MYSQL_DATABASE=otserver
      - MYSQL_USER=otserver
      - MYSQL_PASSWORD=otserver
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
    ports:
      - 3306:3306
    volumes:
      - db-volume:/var/lib/mysql/

  website-nginx:
    image: nginx:latest
    restart: unless-stopped
    ports:
      - 8080:80
    volumes:
      - ./data/web/:/tmp/web/
      - ./:/tmp/otserver/
      - ./data/nginx:/etc/nginx/conf.d/
    depends_on:
      - mysql
      - website-php
    links:
      - website-php

  website-php:
    image: php:7-fpm
    volumes:
      - ./data/web/:/tmp/web/
    depends_on:
      - mysql

  login:
    build:
      context: ../
      dockerfile: docker/login/Dockerfile
    restart: unless-stopped
    volumes:
      - ./docker/data/:/tmp/
    ports:
      - 80:8080
    depends_on:
      - mysql

volumes:
  db-volume:
